# Generated by Django 5.2.3 on 2025-07-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('number_of_places', models.PositiveIntegerField(default=0, verbose_name='Количество мест')),
                ('number_of_suw_hours', models.IntegerField(choices=[(0, '0'), (2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12')], default=0, verbose_name='Количество ОПТ')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Посетил')),
            ],
            options={
                'verbose_name': 'Посещение мероприятия',
                'verbose_name_plural': 'Посещения мероприятий',
                'ordering': ['student__user__last_name', 'student__user__first_name'],
            },
        ),
    ]
