# Generated by Django 5.2.3 on 2025-07-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.worker', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='Мероприятия'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user__role': 'ST'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_events', through='events.EventAttendance', to='users.student', verbose_name='Участники'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('student', 'event')},
        ),
    ]
